import { MemoryItem, EvaluationRun, CausalTimelineNode, ActiveGuardrail, TeamStandard } from './types';

export const SEED_MEMORIES: MemoryItem[] = [
  // ==========================================
  // HERO PATTERN: Unsafe Schema Migrations (orders-service)
  // ==========================================
  {
    id: 'MEM-PR-142',
    bank_id: 'acme-platform',
    title: 'PR #142: Orders analytics index',
    type: 'pr_review',
    service: 'orders-service',
    timestamp: '2026-08-10T14:32:00Z',
    relative_time: 'Aug 10',
    content: `PR #142 reviewed by DB Platform Lead. A reviewer warned about creating an index on high-traffic table 'orders' during peak hours without CONCURRENTLY keyword. The migration attempted "CREATE INDEX idx_orders_region ON orders(customer_region);" which acquires an AccessExclusiveLock blocking concurrent writes.`,
    relevance_note: 'Similar schema change without concurrent execution',
    relevance_score: 0.94,
    metadata: {
      service: 'orders-service',
      type: 'pr_review',
      focus_areas: ['Unsafe DB migration'],
      severity: 'MEDIUM',
      author: 'alex.chen@acme.internal',
      source_id: 'PR-142',
      tags: ['migration', 'postgres', 'indexes', 'orders-service'],
      confidence_score: 85,
    },
    causal_links: {
      caused_by: [],
      resolved_by: ['MEM-PM-024'],
    },
  },
  {
    id: 'MEM-RUN-889',
    bank_id: 'acme-platform',
    title: 'RUN-889: Migration timeout (15m lock threshold)',
    type: 'pipeline_failure',
    service: 'orders-service',
    timestamp: '2026-08-12T09:15:00Z',
    relative_time: 'Aug 12',
    content: `CI/CD Staging pipeline failed at deployment step 'db-migrate-orders'. Adding NOT NULL column 'customer_region' to 'orders' table (42 million rows) caused full table rewrite and exceeded the 15-minute lock threshold. Database connection pool was exhausted, backing up 8,400 queued requests.`,
    relevance_note: 'Matching lock failure during table rewrite and index creation',
    relevance_score: 0.98,
    metadata: {
      service: 'orders-service',
      type: 'pipeline_failure',
      focus_areas: ['Unsafe DB migration'],
      severity: 'HIGH',
      source_id: 'RUN-889',
      environment: 'staging',
      tags: ['lock-timeout', 'not-null-migration', 'table-rewrite', 'connection-exhaustion'],
      confidence_score: 95,
    },
    causal_links: {
      preceded_by: ['MEM-PR-142'],
      caused_by: ['MEM-INC-024'],
    },
  },
  {
    id: 'MEM-INC-024',
    bank_id: 'acme-platform',
    title: 'INC-024: Checkout latency lock contention',
    type: 'incident',
    service: 'checkout-api',
    timestamp: '2026-08-12T10:45:00Z',
    relative_time: 'Aug 12',
    content: `SEV-2 Incident: P99 latency on checkout-api surged from 120ms to 28,400ms due to downstream database lock contention on 'orders' table. Order placement failed for 18% of users over a 22-minute window before emergency rollback was triggered.`,
    relevance_note: 'Downstream production impact caused by lock contention on orders table',
    relevance_score: 0.96,
    metadata: {
      service: 'checkout-api',
      type: 'incident',
      focus_areas: ['Unsafe DB migration'],
      severity: 'SEV-2',
      source_id: 'INC-024',
      environment: 'production',
      tags: ['sev-2', 'checkout-latency', 'orders-lock', 'cascading-failure'],
      confidence_score: 98,
    },
    causal_links: {
      preceded_by: ['MEM-RUN-889'],
      resolved_by: ['MEM-PM-024'],
    },
  },
  {
    id: 'MEM-PM-024',
    bank_id: 'acme-platform',
    title: 'PM-024: Safe migration playbook',
    type: 'post_mortem',
    service: 'orders-service',
    timestamp: '2026-08-13T16:00:00Z',
    relative_time: 'Aug 13',
    content: `Post-Mortem for INC-024: Established the standard 5-step zero-downtime migration rule for PostgreSQL tables with >1M rows:
1. Add new column as NULLABLE.
2. Deploy dual-write / application fallback code.
3. Asynchronously backfill data in batches of 5,000 rows.
4. Build indexes using CREATE INDEX CONCURRENTLY with separate transaction.
5. Add NOT NULL constraint with VALIDATE CONSTRAINT in post-deploy phase.`,
    relevance_note: 'Proven resolution and mandatory team rollout pattern for orders-service',
    relevance_score: 0.99,
    metadata: {
      service: 'orders-service',
      type: 'post_mortem',
      focus_areas: ['Unsafe DB migration'],
      severity: 'HIGH',
      source_id: 'PM-024',
      tags: ['playbook', 'zero-downtime', 'concurrent-indexing', 'standard-policy'],
      confidence_score: 100,
    },
    causal_links: {
      resolved_by: ['MEM-INC-024', 'MEM-RUN-889', 'MEM-PR-142'],
      prevented_by: ['MEM-PR-167'],
    },
  },

  // ==========================================
  // SECONDARY PATTERN: Missing Production Secrets / Env Config
  // ==========================================
  {
    id: 'MEM-PR-108',
    bank_id: 'acme-platform',
    title: 'PR #108: Stripe billing webhook integration',
    type: 'pr_review',
    service: 'payments-service',
    timestamp: '2026-07-15T11:20:00Z',
    relative_time: 'Jul 15',
    content: `PR #108 introduced STRIPE_WEBHOOK_SECRET configuration read directly from process.env without fallback or pre-flight schema validation in payments-service.`,
    relevance_note: 'Missing environment secret validation before deploy',
    relevance_score: 0.88,
    metadata: {
      service: 'payments-service',
      type: 'pr_review',
      focus_areas: ['Missing secret'],
      severity: 'MEDIUM',
      source_id: 'PR-108',
      tags: ['secrets', 'stripe', 'env-vars'],
      confidence_score: 88,
    },
  },
  {
    id: 'MEM-RUN-612',
    bank_id: 'acme-platform',
    title: 'RUN-612: Container CrashLoopBackOff on missing STRIPE_SIGNING_KEY',
    type: 'pipeline_failure',
    service: 'payments-service',
    timestamp: '2026-07-16T08:40:00Z',
    relative_time: 'Jul 16',
    content: `Staging deployment failed: Kubernetes pods for payments-service crashed on startup with TypeError: Cannot read property 'startsWith' of undefined. Environment variable STRIPE_SIGNING_KEY was not populated in Vault secret mapping.`,
    relevance_note: 'Unvalidated secret caused immediate CrashLoopBackOff in staging container',
    relevance_score: 0.92,
    metadata: {
      service: 'payments-service',
      type: 'pipeline_failure',
      focus_areas: ['Missing secret'],
      severity: 'HIGH',
      source_id: 'RUN-612',
      tags: ['crashloop', 'vault', 'missing-secret'],
      confidence_score: 94,
    },
  },
  {
    id: 'MEM-PM-019',
    bank_id: 'acme-platform',
    title: 'PM-019: Mandatory Envalid schema on all container startups',
    type: 'post_mortem',
    service: 'payments-service',
    timestamp: '2026-07-18T15:00:00Z',
    relative_time: 'Jul 18',
    content: `Incident PM-019 established that every Node/Go/Rust microservice must use a strict startup schema validator (e.g. envalid / zod) to fail fast during CI smoke tests rather than during Kubernetes rolling updates.`,
    relevance_note: 'Standardized secret contract enforcement across all services',
    relevance_score: 0.91,
    metadata: {
      service: 'payments-service',
      type: 'post_mortem',
      focus_areas: ['Missing secret'],
      severity: 'HIGH',
      source_id: 'PM-019',
      tags: ['secret-guard', 'envalid', 'zod', 'vault-sync'],
      confidence_score: 96,
    },
  },

  // ==========================================
  // THIRD PATTERN: Dependency Upgrade Incompatibility
  // ==========================================
  {
    id: 'MEM-PR-205',
    bank_id: 'acme-platform',
    title: 'PR #205: Bump Prisma ORM from v5.2 to v6.0',
    type: 'pr_review',
    service: 'inventory-service',
    timestamp: '2026-08-01T13:10:00Z',
    relative_time: 'Aug 1',
    content: `Major version upgrade for Prisma in inventory-service caused silent connection pool exhaustion because Prisma 6 removed default connection reuse in serverless lambdas.`,
    relevance_note: 'Major ORM upgrade caused hidden concurrency regressions',
    relevance_score: 0.85,
    metadata: {
      service: 'inventory-service',
      type: 'pr_review',
      focus_areas: ['Dependency upgrade'],
      severity: 'MEDIUM',
      source_id: 'PR-205',
      tags: ['prisma', 'dependency-upgrade', 'breaking-change'],
      confidence_score: 86,
    },
  },
  {
    id: 'MEM-RUN-904',
    bank_id: 'acme-platform',
    title: 'RUN-904: Connection pool saturation under load test',
    type: 'pipeline_failure',
    service: 'inventory-service',
    timestamp: '2026-08-02T16:25:00Z',
    relative_time: 'Aug 2',
    content: `Load testing stage failed with PrismaClientInitializationError: Timed out fetching a new connection from the pool. Required setting pool_timeout=30 and pgbouncer=true in connection string.`,
    relevance_note: 'Database connection saturation during major ORM bump',
    relevance_score: 0.89,
    metadata: {
      service: 'inventory-service',
      type: 'pipeline_failure',
      focus_areas: ['Dependency upgrade'],
      severity: 'HIGH',
      source_id: 'RUN-904',
      tags: ['connection-pool', 'load-test-failure', 'orm-regression'],
      confidence_score: 90,
    },
  },

  // ==========================================
  // AUTH & API CONTRACT PATTERNS
  // ==========================================
  {
    id: 'MEM-INC-015',
    bank_id: 'acme-platform',
    title: 'INC-015: JWT signature key rotation clock skew',
    type: 'incident',
    service: 'auth-service',
    timestamp: '2026-06-20T22:10:00Z',
    relative_time: 'Jun 20',
    content: `SEV-1 Incident: Rotating JWKS public keys without a 24-hour dual-verification window caused 401 Unauthorized for 100% of mobile clients holding tokens signed with key-id 2026-Q2.`,
    relevance_note: 'Key rotation requires dual-key overlapping validity period',
    relevance_score: 0.83,
    metadata: {
      service: 'auth-service',
      type: 'incident',
      focus_areas: ['API contract change'],
      severity: 'SEV-1',
      source_id: 'INC-015',
      tags: ['auth', 'jwks', 'jwt-rotation', 'sev-1'],
      confidence_score: 97,
    },
  },
  {
    id: 'MEM-PR-312',
    bank_id: 'acme-platform',
    title: 'PR #312: Add idempotency header to /checkout/v2',
    type: 'pr_review',
    service: 'checkout-api',
    timestamp: '2026-08-25T17:00:00Z',
    relative_time: 'Aug 25',
    content: `PR #312 added Idempotency-Key validation with Redis distributed locking. Validated against past double-charge incidents. Approved clean.`,
    relevance_note: 'Best practice implementation of payment idempotency',
    relevance_score: 0.80,
    metadata: {
      service: 'checkout-api',
      type: 'pr_review',
      focus_areas: ['API contract change'],
      severity: 'LOW',
      source_id: 'PR-312',
      tags: ['idempotency', 'checkout', 'redis-lock'],
      confidence_score: 92,
    },
  },
  {
    id: 'MEM-STD-001',
    bank_id: 'acme-platform',
    title: 'STD-001: Zero-Downtime PostgreSQL Schema Standards',
    type: 'standard',
    service: 'all-services',
    timestamp: '2026-08-14T10:00:00Z',
    relative_time: 'Aug 14',
    content: `Mandatory standard: Any ALTER TABLE that adds NOT NULL or creates indexes on tables exceeding 1M rows must follow the concurrent non-blocking rollout lifecycle.`,
    relevance_note: 'Inferred team standard from PM-024 and RUN-889',
    relevance_score: 0.95,
    metadata: {
      service: 'all-services',
      type: 'standard',
      focus_areas: ['Unsafe DB migration'],
      severity: 'HIGH',
      source_id: 'STD-001',
      tags: ['standard', 'zero-downtime', 'postgres'],
      confidence_score: 99,
    },
  },
];

export const INITIAL_EVALUATION_RUNS: EvaluationRun[] = [
  {
    id: 'run-167',
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    relative_time: '2 min ago',
    status: 'HIGH RISK',
    title: 'PR #167: Add customer-region analytics',
    service: 'orders-service',
    environment: 'Production',
    policy: 'Strict production policy',
    focus_areas: ['Unsafe DB migration'],
    file_name: 'migration_v167.sql',
    language: 'PostgreSQL',
    code_snippet: `ALTER TABLE orders ADD COLUMN customer_region VARCHAR(50) NOT NULL;\nCREATE INDEX idx_orders_region ON orders(customer_region);`,
    memory_enabled: true,
    retrieved_memories_count: 4,
    retrieved_memory_ids: ['MEM-PR-142', 'MEM-RUN-889', 'MEM-INC-024', 'MEM-PM-024'],
    execution_latency_ms: 412,
    output: {
      risk_score: 82,
      risk_level: 'High',
      provenance_note: 'Detected before merge using historical migration patterns',
      summary: 'High risk deployment detected: adding a direct NOT NULL column and non-concurrent index to the orders table will trigger an AccessExclusiveLock, matching the failure signature of RUN-889 and INC-024.',
      memory_enabled: true,
      findings: [
        {
          id: 'FINDING-1',
          severity: 'HIGH',
          title: 'Adding NOT NULL column directly blocks database writes on orders during schema application.',
          description: 'In PostgreSQL, ALTER TABLE ... ADD COLUMN ... NOT NULL without a default or backfill acquires an AccessExclusiveLock and rewrites the table. With 42M rows in orders-service, this will exceed lock timeouts.',
          source_memory_ids: ['MEM-RUN-889', 'MEM-INC-024'],
        },
        {
          id: 'FINDING-2',
          severity: 'HIGH',
          title: 'Index creation locks the main orders table, causing replication lag similar to the incident in RUN-889.',
          description: 'Executing CREATE INDEX without the CONCURRENTLY modifier holds a ShareLock preventing table writes until index building completes.',
          source_memory_ids: ['MEM-PR-142', 'MEM-RUN-889'],
        },
        {
          id: 'FINDING-3',
          severity: 'MEDIUM',
          title: 'Rollback path is incomplete; no script provided to revert the column safely.',
          description: 'No companion downgrade migration provided to drop the index and remove the column if application deployment halts.',
          source_memory_ids: ['MEM-PM-024'],
        },
      ],
      ci_checks: [
        {
          id: 'CI-1',
          title: 'PostgreSQL Migration Lock Guardrail',
          description: 'Block direct ALTER TABLE ADD COLUMN NOT NULL on tables > 1M rows in CI migration tests.',
          type: 'migration-guard',
          snippet: `name: pg-migration-guard\non: pull_request\njobs:\n  lint-sql:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: squawkhq/squawk-action@v1\n        with:\n          rules: 'require-concurrent-index,require-nullable-column'`,
        },
        {
          id: 'CI-2',
          title: 'Zero-Downtime Rollout Assertion',
          description: 'Enforce presence of rollback script for any DDL modification.',
          type: 'linter',
        },
      ],
      safer_rollout: [
        '1. Add the new column as nullable first.',
        '2. Deploy safe write-path updates to populate region on insert.',
        '3. Backfill existing rows in manageable batches.',
        '4. Create the index CONCURRENTLY to avoid locks.',
        '5. Validate and enforce NOT NULL with a migration post-deploy.',
      ],
      memory_citations: [
        {
          memory_id: 'MEM-PR-142',
          title: 'PR #142: Orders analytics index',
          type: 'pr_review',
          date: 'Aug 10',
          relevance_note: 'Similar schema change',
          service: 'orders-service',
        },
        {
          memory_id: 'MEM-RUN-889',
          title: 'RUN-889: Migration timeout (15m lock threshold)',
          type: 'pipeline_failure',
          date: 'Aug 12',
          relevance_note: 'Matching lock failure',
          service: 'orders-service',
        },
        {
          memory_id: 'MEM-INC-024',
          title: 'INC-024: Checkout latency lock contention',
          type: 'incident',
          date: 'Aug 12',
          relevance_note: 'Downstream production impact',
          service: 'checkout-api',
        },
        {
          memory_id: 'MEM-PM-024',
          title: 'PM-024: Safe migration playbook',
          type: 'post_mortem',
          date: 'Aug 13',
          relevance_note: 'Proven resolution',
          service: 'orders-service',
        },
      ],
      why_recommendation: 'Findings #1 and #2 directly draw on RUN-889 and INC-024, where an identical synchronous NOT NULL column addition locked the orders table and caused a 22-minute checkout outage. Safer rollout steps 1-5 replicate the validated playbook from PM-024.',
    },
  },
  {
    id: 'run-889',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    relative_time: 'Yesterday',
    status: 'LEARNED',
    title: 'RUN-889: Migration timeout',
    service: 'orders-service',
    environment: 'Staging',
    policy: 'Strict production policy',
    focus_areas: ['Unsafe DB migration'],
    file_name: 'db_migration_patch.sql',
    language: 'PostgreSQL',
    code_snippet: `ALTER TABLE orders ADD COLUMN legacy_region_code INT NOT NULL;`,
    memory_enabled: true,
    retrieved_memories_count: 2,
    retrieved_memory_ids: ['MEM-PR-142', 'MEM-PM-024'],
    execution_latency_ms: 380,
    output: {
      risk_score: 76,
      risk_level: 'High',
      provenance_note: 'Staging pipeline failure recorded as learned organizational memory',
      summary: 'Staging migration failure captured and indexed to prevent future production lock contention.',
      memory_enabled: true,
      findings: [
        {
          id: 'FINDING-1',
          severity: 'HIGH',
          title: 'Lock timeout exceeded on orders staging table during full table lock.',
          description: 'Process was terminated by Postgres statement_timeout.',
        },
      ],
      ci_checks: [],
      safer_rollout: ['Split migration into dual-phase deploy.'],
      memory_citations: [
        {
          memory_id: 'MEM-PR-142',
          title: 'PR #142: Orders analytics index',
          type: 'pr_review',
          date: 'Aug 10',
          relevance_note: 'Prior warning in review',
          service: 'orders-service',
        },
      ],
      why_recommendation: 'Captured staging lock timeout to reinforce the schema migration causal pattern.',
    },
  },
  {
    id: 'run-024',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    relative_time: 'Aug 12',
    status: 'RESOLVED',
    title: 'INC-024: Checkout latency',
    service: 'checkout-api',
    environment: 'Production',
    policy: 'Strict production policy',
    focus_areas: ['Unsafe DB migration'],
    file_name: 'incident_report_024.md',
    language: 'Markdown',
    code_snippet: `Root cause: Downstream database lock contention on orders table during peak hours.`,
    memory_enabled: true,
    retrieved_memories_count: 3,
    retrieved_memory_ids: ['MEM-RUN-889', 'MEM-PM-024'],
    execution_latency_ms: 450,
    output: {
      risk_score: 94,
      risk_level: 'High',
      provenance_note: 'SEV-2 Incident resolved and compiled into PM-024',
      summary: 'SEV-2 incident resolved. Post-mortem validated zero-downtime standard.',
      memory_enabled: true,
      findings: [
        {
          id: 'FINDING-1',
          severity: 'HIGH',
          title: 'P99 latency degraded to 28,400ms during orders lock.',
          description: 'Cascading timeout in checkout-api worker pool.',
        },
      ],
      ci_checks: [],
      safer_rollout: ['Execute PM-024 playbook steps.'],
      memory_citations: [
        {
          memory_id: 'MEM-PM-024',
          title: 'PM-024: Safe migration playbook',
          type: 'post_mortem',
          date: 'Aug 13',
          relevance_note: 'Playbook validated in resolution',
          service: 'orders-service',
        },
      ],
      why_recommendation: 'Incident closed and converted to active team guardrail.',
    },
  },
];

export const TIMELINE_NODES: CausalTimelineNode[] = [
  {
    id: 'TL-1',
    date: 'Aug 10',
    title: 'PR #142 — Risk warning issued',
    subtitle: 'A reviewer flagged a blocking index on the orders table.',
    type: 'CODE REVIEW',
    type_badge_color: 'purple',
    service: 'orders-service',
    is_active_pattern_member: true,
    details: 'Initial review on orders-service identified direct index creation risk.',
  },
  {
    id: 'TL-2',
    date: 'Aug 12',
    title: 'RUN-889 — Production deployment rolled back',
    subtitle: 'Migration lock duration exceeded threshold.',
    type: 'PIPELINE FAILURE',
    type_badge_color: 'red',
    service: 'orders-service',
    is_active_pattern_member: true,
    details: 'Staging lock timeout exceeded 15 minutes during ALTER TABLE rewrite.',
  },
  {
    id: 'TL-3',
    date: 'Aug 12',
    title: 'INC-024 — Checkout latency incident',
    subtitle: 'Database lock contention affected live checkout traffic.',
    type: 'SEV-2 INCIDENT',
    type_badge_color: 'pink',
    service: 'checkout-api',
    is_active_pattern_member: true,
    details: 'Checkout-api P99 latency breached SLA due to locked orders table.',
  },
  {
    id: 'TL-4',
    date: 'Aug 13',
    title: 'PM-024 — Safe migration playbook validated',
    subtitle: 'Nullable field, batch backfill, then concurrent indexing.',
    type: 'PROVEN RESOLUTION',
    type_badge_color: 'green',
    service: 'orders-service',
    is_active_pattern_member: true,
    details: 'Engineering team codified the 5-step zero-downtime Postgres playbook.',
  },
  {
    id: 'TL-5',
    date: 'Today',
    title: 'PR #167 — Repeat risk caught before merge',
    subtitle: 'MergeGuard used historical evidence to recommend a safer rollout.',
    type: 'PREVENTED RISK',
    type_badge_color: 'cyan',
    service: 'orders-service',
    is_active_pattern_member: true,
    details: 'ReVise intercepted PR #167 before staging, saving an estimated 25-minute outage.',
  },
];

export const ACTIVE_GUARDRAILS: ActiveGuardrail[] = [
  {
    id: 'GUARD-1',
    pattern_name: 'Orders-service: migration risk pattern',
    service: 'orders-service',
    related_events_count: 3,
    description: 'Schema changes on high-traffic tables repeatedly caused lock-duration risk. Hindsight protects future deployments against this specific signature.',
    policy_title: 'Zero-Downtime PostgreSQL Migration Policy',
    policy_rules: [
      '1. NEVER execute ALTER TABLE ADD COLUMN NOT NULL without a default or prior backfill on tables > 1,000,000 rows.',
      '2. ALWAYS create indexes with the CONCURRENTLY modifier in an isolated transaction.',
      '3. Enforce a statement_timeout = 5s on all DDL migrations in CI/CD pipeline.',
      '4. Provide an automated rollback DDL script in every migration PR.',
    ],
    example_fix_snippet: `-- Step 1: Add nullable column\nALTER TABLE orders ADD COLUMN customer_region VARCHAR(50);\n\n-- Step 2: Create index concurrently\nCREATE INDEX CONCURRENTLY idx_orders_region ON orders(customer_region);\n\n-- Step 3: Backfill & validate NOT NULL in post-deploy migration`,
  },
  {
    id: 'GUARD-2',
    pattern_name: 'Payments-service: startup secret validation',
    service: 'payments-service',
    related_events_count: 2,
    description: 'Missing environment configuration variables caused CrashLoopBackOff in staging. Hindsight enforces strict schema validation on all entrypoints.',
    policy_title: 'Environment Secret Validation Policy',
    policy_rules: [
      '1. All third-party payment gateway keys must be declared in the Envalid / Zod schema.',
      '2. CI smoke tests must verify Vault secret mapping prior to Helm release deployment.',
    ],
    example_fix_snippet: `import { cleanEnv, str } from 'envalid';\nexport const env = cleanEnv(process.env, {\n  STRIPE_WEBHOOK_SECRET: str({ desc: 'Stripe webhook signature secret' }),\n});`,
  },
];

export const TEAM_STANDARDS: TeamStandard[] = [
  {
    id: 'STD-1',
    title: 'Always create indexes CONCURRENTLY on tables > 1M rows',
    description: 'Direct index creation acquires ShareLock on the entire table, blocking all INSERT, UPDATE, and DELETE operations. Concurrent index creation allows live traffic to proceed without write stalls.',
    service: 'orders-service',
    category: 'Database',
    enforcement_level: 'Strict Production Blocker',
    confidence_score: 98,
    inferred_from: {
      source_ids: ['PM-024', 'INC-024', 'RUN-889'],
      incident_names: ['INC-024: Checkout Latency Outage', 'RUN-889: Migration Timeout'],
    },
    rule_snippet: `CREATE INDEX CONCURRENTLY idx_name ON table_name(column_name);`,
    updated_at: 'Aug 14, 2026',
  },
  {
    id: 'STD-2',
    title: 'Never add NOT NULL columns synchronously on high-traffic tables',
    description: 'Adding a non-nullable column forces a full table lock and row-by-row table rewrite. Follow the 3-step phased rollout: (1) Add nullable, (2) Backfill batches, (3) Validate NOT NULL constraint.',
    service: 'orders-service',
    category: 'Database',
    enforcement_level: 'Strict Production Blocker',
    confidence_score: 96,
    inferred_from: {
      source_ids: ['PM-024', 'PR-142'],
      incident_names: ['PM-024: Safe Migration Playbook'],
    },
    rule_snippet: `ALTER TABLE orders ADD COLUMN region VARCHAR(50); -- Phase 1\n-- Phase 2 backfill\nALTER TABLE orders ADD CONSTRAINT check_region CHECK (region IS NOT NULL) NOT VALID; -- Phase 3`,
    updated_at: 'Aug 14, 2026',
  },
  {
    id: 'STD-3',
    title: 'Mandatory fail-fast startup secret validation (Zod/Envalid)',
    description: 'Every container entrypoint must validate required Vault secrets during boot. Prevents partial deployments and silent runtime null dereferences.',
    service: 'payments-service',
    category: 'Secrets',
    enforcement_level: 'Mandatory CI Check',
    confidence_score: 94,
    inferred_from: {
      source_ids: ['PM-019', 'RUN-612'],
      incident_names: ['INC-019: Stripe Webhook Auth Crash'],
    },
    rule_snippet: `const EnvSchema = z.object({ STRIPE_KEY: z.string().min(10) });\nEnvSchema.parse(process.env);`,
    updated_at: 'Jul 18, 2026',
  },
  {
    id: 'STD-4',
    title: 'Mandatory Idempotency Keys on Payment & Mutation Endpoints',
    description: 'All state-changing endpoints in payments-service and checkout-api must accept and enforce an Idempotency-Key header backed by Redis TTL locks.',
    service: 'checkout-api',
    category: 'API Design',
    enforcement_level: 'Mandatory CI Check',
    confidence_score: 91,
    inferred_from: {
      source_ids: ['PR-312'],
      incident_names: ['Double-Charge Safeguard Initiative'],
    },
    rule_snippet: `POST /v2/charges\nHeaders: Idempotency-Key: req_uuid_v4`,
    updated_at: 'Aug 25, 2026',
  },
  {
    id: 'STD-5',
    title: 'Lock Connection Pool Max Limits during Major ORM Upgrades',
    description: 'When bumping ORM major versions (e.g. Prisma 5 -> 6), load tests must run with pgbouncer transaction pooling and strict connection timeouts.',
    service: 'inventory-service',
    category: 'Dependencies',
    enforcement_level: 'Recommended Review',
    confidence_score: 87,
    inferred_from: {
      source_ids: ['RUN-904', 'PR-205'],
      incident_names: ['RUN-904: Connection Pool Saturation'],
    },
    rule_snippet: `DATABASE_URL="postgres://...?connection_limit=20&pool_timeout=10"`,
    updated_at: 'Aug 2, 2026',
  },
];

export const DEMO_SCENARIOS = [
  {
    id: 'scenario-unsafe-db',
    category: 'HIGH-RISK CHANGE',
    categoryColor: 'red',
    title: 'Unsafe DB migration',
    description: 'Assess a schema migration for production lock risk.',
    service: 'orders-service',
    environment: 'Production' as const,
    policy: 'Strict production policy',
    focusArea: 'Unsafe DB migration' as const,
    fileName: 'migration_v167.sql',
    language: 'PostgreSQL',
    prTitle: 'PR #167: Add customer-region analytics to orders',
    code: `ALTER TABLE orders ADD COLUMN customer_region VARCHAR(50) NOT NULL;\nCREATE INDEX idx_orders_region ON orders(customer_region);`,
  },
  {
    id: 'scenario-missing-secret',
    category: 'PIPELINE RELIABILITY',
    categoryColor: 'purple',
    title: 'Missing production secret',
    description: 'Prevent recurring environment configuration failures.',
    service: 'payments-service',
    environment: 'Production' as const,
    policy: 'Strict production policy',
    focusArea: 'Missing secret' as const,
    fileName: 'stripe_webhook_handler.ts',
    language: 'TypeScript',
    prTitle: 'PR #188: Direct Stripe webhook handler for refund reconciliation',
    code: `import express from 'express';\n\nexport const handleStripeWebhook = (req: express.Request, res: express.Response) => {\n  const sig = req.headers['stripe-signature'] as string;\n  // Direct access without startup schema check\n  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET!;\n  \n  const event = stripe.webhooks.constructEvent(req.body, sig, webhookSecret);\n  res.json({ received: true });\n};`,
  },
  {
    id: 'scenario-dependency-upgrade',
    category: 'CHANGE INTELLIGENCE',
    categoryColor: 'blue',
    title: 'Dependency upgrade',
    description: 'Check prior compatibility failures before deployment.',
    service: 'inventory-service',
    environment: 'Production' as const,
    policy: 'Standard review',
    focusArea: 'Dependency upgrade' as const,
    fileName: 'package.json',
    language: 'JSON',
    prTitle: 'PR #224: Upgrade @prisma/client to 6.2.0 and enable telemetry',
    code: `{\n  "name": "inventory-service",\n  "dependencies": {\n    "@prisma/client": "^6.2.0",\n    "prisma": "^6.2.0",\n    "express": "^4.21.0"\n  }\n}`,
  },
];
