import { useEffect, useState, type FormEvent } from "react";
import { Badge, Button, Card, CodeBlock, DiffViewer, EngineeringSignal, FindingCard, Heading, Input, MemoryEvidence, RecommendationCard, RiskScore, SectionHeader, Select, Tabs, Text, Textarea, Toast, TypingIndicator } from "../components/ui";
import { demoReview, standards as demoStandards } from "../mocks/data";
import { getStandards, saveSettings, sendPairMessage } from "../services/revise";
import type { EngineeringStandard } from "../types";

const editorCode = `import { validateSession } from "./validate"

export async function updateSession(input: SessionInput) {
  const current = await getSession(input.sessionId)
  await applySessionMutation(current, input)

  if (!validateSession(current)) {
    throw new AuthenticationError()
  }

  return current
}`;

export function PairProgrammerPage() {
  const [mobileTab, setMobileTab] = useState("Editor");
  const [message, setMessage] = useState("");
  const [reply, setReply] = useState("I found one relevant authentication decision in this file. Ask me to explain it or apply a safer ordering.");
  const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!message) return; setLoading(true); setReply(await sendPairMessage(message)); setMessage(""); setLoading(false); }
  const files = <Card className="h-full p-3"><Text className="mb-3 px-2 font-mono text-[10px] uppercase tracking-wider text-muted">Files</Text>{["src/auth/session.ts", "src/api/review.ts", "src/memory/recall.ts", "src/services/github.ts", "README.md"].map((file, index) => <Button key={file} variant="ghost" className={`w-full justify-start px-2 font-mono text-xs ${index === 0 ? "bg-brand-soft text-brand" : ""}`}>{file}</Button>)}</Card>;
  const editor = <Card className="h-full min-w-0 p-0"><div className="flex items-center justify-between border-b border-line px-4 py-2"><span className="font-mono text-xs text-ink">session.ts</span><Badge tone="warning">1 issue</Badge></div><div className="max-h-[37rem] overflow-auto"><CodeBlock code={editorCode}/></div></Card>;
  const assistant = <Card className="flex h-full min-h-[36rem] flex-col p-0"><div className="border-b border-line p-4"><div className="flex items-center justify-between"><Heading level={3} className="text-sm">AI Pair Programmer</Heading><Badge tone="brand">Aider connected</Badge></div><Text className="mt-1 text-xs text-muted">Context: session.ts · ReVise memory active</Text></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{loading ? <TypingIndicator/> : <div key={reply} className="message-motion rounded-md bg-surface-raised p-3 text-sm leading-6 text-muted">{reply}</div>}<div className="rounded-md border border-brand/25 bg-brand-soft p-3"><Text className="text-xs font-semibold text-brand">Using 3 relevant engineering memories</Text><div className="mt-2 space-y-2 font-mono text-[10px] text-muted"><Text className="memory-chip">Previous authentication decision · 94%</Text><Text className="memory-chip">Team coding standard · 89%</Text><Text className="memory-chip">Previous review feedback · 87%</Text></div></div><RecommendationCard title="Validate before mutation" detail="Move validateSession above applySessionMutation to match the team’s fail-closed authentication standard."/></div><form onSubmit={submit} className="border-t border-line p-3"><Textarea aria-label="Ask pair programmer" className="min-h-20" placeholder="Ask ReVise about this code…" value={message} onChange={event => setMessage(event.target.value)}/><Button className="mt-2 w-full" disabled={loading}>{loading ? "Thinking with memory…" : "Send message"}</Button></form></Card>;
  return <div className="animate-enter"><SectionHeader eyebrow="Memory-aware coding" title="AI Pair Programmer" action={<Badge tone="brand">3 memories in context</Badge>}/><div className="mb-4 lg:hidden"><Tabs tabs={["Files", "Editor", "Assistant"]} active={mobileTab} onChange={setMobileTab}/></div><div className="hidden h-[calc(100vh-10rem)] min-h-[38rem] grid-cols-[13rem_minmax(0,1fr)_22rem] gap-3 lg:grid">{files}{editor}{assistant}</div><div className="lg:hidden">{mobileTab === "Files" ? files : mobileTab === "Editor" ? editor : assistant}</div></div>;
}

export function ReportPage() {
  const review = demoReview;
  return <div className="space-y-8 animate-enter"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge tone="brand">Review report · PR #42</Badge><Heading level={1} className="mt-3 text-3xl">Harden session recall and review pipeline</Heading><Text className="mt-2 text-sm text-muted">YuvrajM2506/ReVise · Generated today at 09:42</Text></div><RiskScore risk={review.risk}/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card><Text className="text-xs text-muted">Overall risk</Text><Text className="mt-2 font-mono text-xl">24 / 100</Text></Card><Card><Text className="text-xs text-muted">Findings</Text><Text className="mt-2 font-mono text-xl">3</Text></Card><Card><Text className="text-xs text-muted">Memory matches</Text><Text className="mt-2 font-mono text-xl text-brand">4</Text></Card><Card><Text className="text-xs text-muted">Standards checked</Text><Text className="mt-2 font-mono text-xl">12</Text></Card></div><Card><SectionHeader eyebrow="Review summary" title="Assessment"/><Text className="max-w-4xl text-sm leading-7 text-muted">{review.summary}</Text></Card><section><SectionHeader title="Findings"/><div className="grid gap-3">{review.findings.map(item => <FindingCard key={item.id} finding={item}/>)}</div></section><section><SectionHeader title="Memory Evidence"/><div className="grid gap-3 md:grid-cols-2">{review.memories.map(item => <MemoryEvidence key={item.id} evidence={item}/>)}</div></section><div className="grid gap-6 lg:grid-cols-2"><Card><SectionHeader title="Engineering Signals"/><EngineeringSignal label="Security" value="78 / 100" trend="One validation-order issue"/><EngineeringSignal label="Performance" value="96 / 100" trend="No regression detected"/><EngineeringSignal label="Code quality" value="91 / 100" trend="One configuration suggestion"/></Card><div><SectionHeader title="Recommended Actions"/><div className="space-y-3"><RecommendationCard title="Resolve authentication ordering" detail="Block merge until validation happens before session mutation."/><RecommendationCard title="Add idempotency key" detail="Prevent duplicate findings when the model provider retries."/></div></div></div><section><SectionHeader title="Change impact"/><Card><div className="mb-4 flex h-24 items-end gap-2">{[30, 52, 44, 74, 58, 86, 62, 45, 68, 82].map((height, index) => <div key={index} className="flex-1 rounded-t bg-brand/30" style={{ height: `${height}%` }}/>)}</div><Text className="font-mono text-xs text-muted">Security · Performance · Code quality signals across changed files</Text></Card></section></div>;
}

export function StandardsPage() {
  const [standards, setStandards] = useState<EngineeringStandard[]>(demoStandards);
  const [group, setGroup] = useState("All");
  useEffect(() => { getStandards().then(setStandards); }, []);
  const groups = ["All", "Engineering", "Security", "Performance", "Architecture", "Team Preferences"];
  const shown = group === "All" ? standards : standards.filter(item => item.category === group);
  return <div className="animate-enter"><SectionHeader eyebrow="Review policy" title="Engineering Standards" action={<Badge tone="brand">{standards.length} active</Badge>}/><Text className="-mt-2 mb-6 max-w-2xl text-sm leading-6 text-muted">Durable rules ReVise recalls during code review. Confidence grows when feedback and outcomes reinforce a standard.</Text><Tabs tabs={groups} active={group} onChange={setGroup}/><div className="mt-6 grid gap-3 lg:grid-cols-2">{shown.map(item => <Card key={item.id}><div className="flex items-start justify-between gap-3"><div><Badge>{item.category}</Badge><Heading level={3} className="mt-3 text-base">{item.title}</Heading></div><span className="font-mono text-sm text-brand">{item.confidence}%</span></div><Text className="mt-2 text-sm leading-6 text-muted">{item.description}</Text><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-line pt-3 font-mono text-[10px] uppercase text-muted"><span>Used {item.usageCount} times</span><span>{item.source}</span><span>Reinforced {item.lastReinforced}</span></div></Card>)}</div></div>;
}

const settingTabs = ["General", "Repository", "AI Model", "Memory", "Integrations", "Review Preferences", "Notifications", "Appearance"];
export function SettingsPage() {
  const [tab, setTab] = useState("General");
  const [saved, setSaved] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await saveSettings(data); setSaved(true); window.setTimeout(() => setSaved(false), 2500); }
  return <div className="animate-enter"><SectionHeader eyebrow="Workspace configuration" title="Settings"/><div className="grid gap-5 lg:grid-cols-[14rem_1fr]"><Card className="h-fit p-2">{settingTabs.map(item => <Button key={item} variant="ghost" onClick={() => setTab(item)} className={`w-full justify-start ${tab === item ? "bg-brand-soft text-brand" : ""}`}>{item}</Button>)}</Card><Card className="max-w-3xl p-5"><Heading level={2} className="text-lg">{tab}</Heading><Text className="mt-1 text-sm text-muted">Configure {tab.toLowerCase()} preferences for this ReVise workspace.</Text><form onSubmit={submit} className="mt-6 space-y-5"><div><Text as="label" className="mb-2 block text-sm font-medium">{tab === "Repository" ? "Default repository" : tab === "AI Model" ? "Review model" : "Workspace name"}</Text>{tab === "AI Model" ? <Select name="model" defaultValue="ReVise Review Large"><option>ReVise Review Large</option><option>ReVise Review Fast</option></Select> : <Input name="primary" defaultValue={tab === "Repository" ? "YuvrajM2506/ReVise" : "ReVise Engineering"}/>}</div><div><Text as="label" className="mb-2 block text-sm font-medium">{tab === "Memory" ? "Minimum recall confidence" : "Default review behavior"}</Text><Select name="behavior"><option>{tab === "Memory" ? "80% confidence" : "Memory-informed review"}</option><option>{tab === "Memory" ? "90% confidence" : "Strict standards review"}</option></Select></div><div><Text as="label" className="mb-2 block text-sm font-medium">Notes</Text><Textarea name="notes" placeholder={`Add ${tab.toLowerCase()} guidance for ReVise…`}/></div><Button type="submit">Save changes</Button></form></Card></div><Toast message={saved ? "Settings saved." : undefined}/></div>;
}
